apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echoserver
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructures/echoserver
  prune: true
  dependsOn:
  - name: gateway-api-class
  - name: envoy-gateway
