apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  type: default
  interval: 1h
  url: https://democratic-csi.github.io/charts/