apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-vip-ds
  template:
    metadata:
      labels:
        app: kube-vip-ds
    spec:
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - operator: Exists
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v1.0.2
          imagePullPolicy: IfNotPresent
          args:
            - manager
          env:
            # === Mode / Features ===
            # We only want services; Talos handles API VIP.
            - name: cp_enable
              value: "false"
            - name: svc_enable
              value: "true"

            # Per-service leader election (better distribution)
            - name: svc_election
              value: "true"

            # === VIP config / ARP mode ===
            - name: vip_arp
              value: "true"
            # Interface on your Talos nodes
            - name: vip_interface
              value: "eth0"

            # (Optional) you can drop lb_enable entirely for service-only ARP:
            # - name: lb_enable
            #   value: "false"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_TIME
