apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-vip-ds
  template:
    metadata:
      labels:
        app: kube-vip-ds
    spec:
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - operator: Exists
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v1.0.2
          imagePullPolicy: IfNotPresent
          args:
            - manager
          env:
            # L2/ARP mode
            - name: vip_arp
              value: "true"

            # Enable service LoadBalancers
            - name: lb_enable
              value: "true"

            # One leader *per service* (much better distribution)
            - name: svc_election
              value: "true"

            # Interface on your Talos nodes (adjust if not eth0)
            - name: vip_interface
              value: "eth0"

            # Do NOT manage control-plane VIP (Talos already does this)
            - name: cp_enable
              value: "false"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_TIME
