apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructures/democratic-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m0s