apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway-helm
      version: "v1.6.1"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: envoy-gateway
      interval: 1m
  values:
    kubernetes:
      config:
        envoyGateway:
          gateway:
            controller:
              name: "gateway.envoyproxy.io"
