apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: "v0.5.0"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system
      interval: 1m
  values:
    deployment:
      envoyGateway:
        image:
          tag: v0.5.0
    kubernetes:
      config:
        envoyGateway:
          gateway:
            controller:
              name: "gateway.envoyproxy.io"